rust:
  - changed-files:
      - any-glob-to-any-file:
          - "rust/**"

python:
  - changed-files:
      - any-glob-to-any-file:
          - "python/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
